# Lab 1: Transformations with NumPy
You are now in a Jupyter notebook! It consists of written text, mixed with executable Python code.

You are supposed to read from top to bottom, and fill in code in the Python-blocks as you go.

## 1. Getting started
Familiarize yourself with the [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html). You will need it to solve the following tasks.
Use the text, examples and links in the quickstart guide.

## 2. Get familiar with NumPy
First, import NumPy:

Press `Shift + Enter` to execute and advance to the next block. Repeat for each block. You can click on a block to edit and run the code again.
Press `Ctrl + Enter` to execute the current block without advancing.

In [1]:
import numpy as np

## a) Create vectors and matrices
#### Create the vector `t`

$\mathbf{t} =
\begin{bmatrix}
1 \\
0 \\
3
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#array-creation](https://numpy.org/doc/stable/user/quickstart.html#array-creation)

In [2]:
# TODO: Create the vector `t`
t = np.array([1, 0, 3])
print(f"t = {t}\nshape: {t.shape}\ntype: {type(t)}")

t = [1 0 3]
shape: (3,)
type: <class 'numpy.ndarray'>


It's important to note that the sequence of numbers in a one-dimensional NumPy "vector", like `np.array([1, 2, 3])`, is just numbers in a vector space and therefore neither a row nor a column vector. We can see that its shape is `(3,)`.

In order to use it with linear algebra, we have to explicitly go for a 2D representation.

#### Try to create `t` as a `N x 1` _column_ vector.


In [3]:
# TODO: Create 't' as a 'N x 1' column vector
# Be explicit when you create
row = np.array([[1, 2, 3]])               # 1 row with 3 elements. Note the double brackets.
col = np.array([[1],[2],[3]])             # 3 rows with 1 element each
col2 = np.array([[1, 2, 3]]).T            # Transpose a row vector
print("Explicit")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")
print(f"\nTranspose:\ncol2 = \n{col}, shape: {col2.shape}")

# Use shortcuts when you create
row = np.r_['r', [1,2,3]]                 # shape: (1, 3)
col = np.r_['c', [1,2,3]]                 # shape: (3, 1)
print("\nShortcuts")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")

# Reshape existing data
col = np.array([1,2,3]).reshape(-1, 1)    # Reshape to change the 'view' of the data
row = np.array([1,2,3]).reshape(1, -1)    # Reshape to change the 'view' of the data
print("\nReshape")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")

# Increase the dimension of existing data
arr = np.array([1,2,3])
row = arr[np.newaxis, :]
col = arr[:,np.newaxis]
print("\nIncrease dimension")
print(f"row = {row}, shape: {row.shape}")
print(f"col = \n{col}, shape: {col.shape}")

# We'll go for the one with the least typing
t = np.array([[1, 0, 3]]).T
print(f"\nt = \n{t}\nshape: {t.shape}")

Explicit
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

Transpose:
col2 = 
[[1]
 [2]
 [3]], shape: (3, 1)

Shortcuts
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

Reshape
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

Increase dimension
row = [[1 2 3]], shape: (1, 3)
col = 
[[1]
 [2]
 [3]], shape: (3, 1)

t = 
[[1]
 [0]
 [3]]
shape: (3, 1)


#### Create the matrix `A`

$
\mathbf{A} =
\begin{bmatrix}
1 & 0 & 3\\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$

In [4]:
# TODO: Create the matrix A
A = np.array([[1, 0, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(f"A:\n{A}")

A:
[[1 0 3]
 [4 5 6]
 [7 8 9]]


#### Create the identity matrix I.

$
\mathbf{I}=
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview](https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview)

In [5]:
# TODO: Create the matrix I
I = np.eye(3)
print(f"I:\n{I}")

I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create the matrix T.

$
\mathbf{T} =
\begin{bmatrix}
\mathbf{A} & \mathbf{t} \\
\mathbf{0} & 1
\end{bmatrix}
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays](https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays)
Hint: [https://numpy.org/doc/stable/reference/generated/numpy.block.html](https://numpy.org/doc/stable/reference/generated/numpy.block.html)

In [7]:
# TODO: Create the matrix T
T = np.block([                                  # Using 'block'
    [A, t],
    [0, 0, 0, 1]
])
T2 = np.vstack((np.c_[A, t], [0, 0, 0, 1]))  # Nested stacking

print(f"T = \n{T}\nnp.array_equal(T, T2): {np.array_equal(T, T2)}")

# Stacking: np.c_[A, t] does NOT require 't' to be a column (have two dimensions)
# Block:    np.block([A, t]) does.

T = 
[[1 0 3 1]
 [4 5 6 0]
 [7 8 9 3]
 [0 0 0 1]]
np.array_equal(T, T2): True


#### Create the matrix B.

$
\mathbf{B} = \mathbf{A}^T
$

Hint: [https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array](https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array)

In [8]:
# TODO: Create the matrix B
B = A.T
print(f"A = \n{A}\nB = \n{B}")

A = 
[[1 0 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 4 7]
 [0 5 8]
 [3 6 9]]


## b) Coefficients
Set $t_2 = 2$ and $A_{12} = 2$, so that

   $\mathbf{t} =
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix},
    \:
    \mathbf{A} =
    \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9
    \end{bmatrix}$

Perform the corresponding corrections to **T**, so that we still have

   $\mathbf{T} =
    \begin{bmatrix}
    \mathbf{A} & \mathbf{t} \\
    \mathbf{0} & 1
    \end{bmatrix}$

But hey, what happened to **B**?

In [9]:
# TODO: Solve b)
# Note python is zero indexed, so t_2 is t[1]
t[1] = 2

# In the matrix the indexes are A[row, col]
A[0, 1] = 2

# Update corresponding block in T.
T[:3, :3] = A

print(f"t:\n{t}\nA:\n{A},\nT:\n{T},\nB:\n{B}")

t:
[[1]
 [2]
 [3]]
A:
[[1 2 3]
 [4 5 6]
 [7 8 9]],
T:
[[1 2 3 1]
 [4 5 6 0]
 [7 8 9 3]
 [0 0 0 1]],
B:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## c) Block operations
Extract the row vector

$\mathbf{r}_2 = \begin{bmatrix}A_{21} & A_{22} & A_{23}\end{bmatrix}$

and the column vector

$\mathbf{c}_2 = \begin{bmatrix}A_{12} \\ A_{22} \\ A_{32} \end{bmatrix}$

from **A**.

Extract the submatrix

$\mathbf{T}_{3 \times 4} = \begin{bmatrix}\mathbf{A} & \mathbf{t}\end{bmatrix}$

from **T**.

In [10]:
# TODO: r_2
r_2 = A[np.newaxis, 1, :]
print(f"r_2 = \n{r_2}\n")

# TODO: c_2
c_2 = A[:, 1, np.newaxis]
print(f"c_2 = \n{c_2}\n")

# TODO: T_3x4
T_3x4 = T[0:3]
print(f"T_3x4 = \n{T_3x4}")

r_2 = 
[[4 5 6]]

c_2 = 
[[2]
 [5]
 [8]]

T_3x4 = 
[[1 2 3 1]
 [4 5 6 0]
 [7 8 9 3]]


Set the corresponding blocks in **A** and **T** to all `0` (so that the second row and column in **A** are all 0, and the upper 3x4 matrix in **T** is all 0).

Hint: [https://numpy.org/doc/stable/user/quickstart.html#copies-and-views](https://numpy.org/doc/stable/user/quickstart.html#copies-and-views)

In [11]:
# TODO: set 0
r_2[:] = 0
c_2[:] = 0
T_3x4[:] = 0
print(f"A = \n{A}")
print(f"T = \n{T}")

A = 
[[1 0 3]
 [0 0 0]
 [7 0 9]]
T = 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


## d) Matrix and vector arithmetic
- Add two vectors
- Add two matrices
- Multiply two matrices
- Take the dot product between two vectors
- Take the coefficient-wise multiplication between two matrices

Hint: [https://numpy.org/doc/stable/user/quickstart.html#basic-operations](https://numpy.org/doc/stable/user/quickstart.html#basic-operations)

In [12]:
# TODO: Solve d)
v1 = np.array([1, 2, 3])
v2 = np.array([3, 2, 1])
M = np.arange(10, 19).reshape(3, 3)
M[2, 2] = 5
N = np.eye(3)

print(f"v1: {v1}\nv2: {v2}\n")
print(f"M:\n{M}\nN:\n{N}\n")

# TODO: Compute the sum of two vectors.
print(f"v1 + v2 = {v1 + v2}\n")

# TODO: Compute the sum of two matrices.
print(f"M + N = \n{M + N}\n")

# TODO: Compute the matrix multiplication of two matrices.
print(f"N matrix multiply M =\n{N @ M}\n")

# TODO: Compute the dot product between two vectors.
print(f"v1 dot v2 = {v1.dot(v2)}\n")

# TODO: Compute the element-wise multiplication between two matrices.
print(f"M Element-wise product N =\n{M * N}")


v1: [1 2 3]
v2: [3 2 1]

M:
[[10 11 12]
 [13 14 15]
 [16 17  5]]
N:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

v1 + v2 = [4 4 4]

M + N = 
[[11. 11. 12.]
 [13. 15. 15.]
 [16. 17.  6.]]

N matrix multiply M =
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17.  5.]]

v1 dot v2 = 10

M Element-wise product N =
[[10.  0.  0.]
 [ 0. 14.  0.]
 [ 0.  0.  5.]]


## e) Reductions
- Take the sum of all elements in a matrix
- Compute the minimum value in a matrix
    - Also, find its position in the matrix
- Create a vector that is the maximum of each column in a matrix
- Find the L2-norm of a vector
- Find the number of elements in a vector that is greater than a given value.

In [13]:
# Replace 'None' with valid expressions

# TODO: Take the sum of all elements in a matrix
# https://numpy.org/doc/stable/user/quickstart.html#basic-operations
print(f"sum of A: {A.sum()}")

# TODO: Compute the minimum value in a matrix
# TODO: Also, find its position in the matrix.
print(f"minimum of A: {A.min()} "
      f"at index {A.argmin()}, "
      f"(or {np.unravel_index(A.argmin(), A.shape)} in 2D)")

# TODO: Create a vector that is the maximum of each column in a matrix.
print(f"maximum of each column in A: {A.max(0)}")

# TODO: Find the L2-norm of a vector.
v1 = np.array([1, 1])
print(f"L2 norm of {v1} is {np.linalg.norm(v1)}")

# TODO: Find the number of elements in a vector that is greater than a given value.
# https://numpy.org/doc/stable/user/quickstart.html#changing-the-shape-of-an-array
v2 = np.array([0, 10, 2, 13, 4, 15, 6, 17, 8, 19])
print(f"v2: {v2},\n"
      f"    {(v2 > 10).sum()} elements are greater than 10")

sum of A: 20
minimum of A: 0 at index 1, (or (np.int64(0), np.int64(1)) in 2D)
maximum of each column in A: [7 0 9]
L2 norm of [1 1] is 1.4142135623730951
v2: [ 0 10  2 13  4 15  6 17  8 19],
    4 elements are greater than 10


Now that you have gotten to know NumPy, let's use it to transform images in the [next part of the lab](lab_01_transformations.ipynb)!